export const COMPANY_REGISTER_REQUEST = 'COMPANY_REGISTER_REQUEST';
export const COMPANY_REGISTER_SUCCESS = 'COMPANY_REGISTER_SUCCESS';
export const COMPANY_REGISTER_FAIL = 'COMPANY_REGISTER_FAIL';
export const COMPANY_REGISTER_RESET = "COMPANY_REGISTER_RESET";

// companyConstants.js

export const COMPANY_SIGNIN_REQUEST = 'COMPANY_SIGNIN_REQUEST';
export const COMPANY_SIGNIN_SUCCESS = 'COMPANY_SIGNIN_SUCCESS';
export const COMPANY_SIGNIN_FAILURE = 'COMPANY_SIGNIN_FAILURE';
export const COMPANY_SIGNIN_RESET = "COMPANY_SIGNIN_RESET";

export const COMPANY_LOGOUT_REQUEST = "COMPANY_LOGOUT_REQUEST";
export const COMPANY_LOGOUT_SUCCESS = "COMPANY_LOGOUT_SUCCESS";
export const COMPANY_LOGOUT_FAIL = "COMPANY_LOGOUT_FAIL";
export const COMPANY_LOGOUT_RESET = "COMPANY_LOGOUT_RESET";

export const COMPANY_JOBS_REQUEST = 'COMPANY_JOBS_REQUEST';
export const COMPANY_JOBS_SUCCESS = 'COMPANY_JOBS_SUCCESS';
export const COMPANY_JOBS_FAIL = 'COMPANY_JOBS_FAIL';

export const COMPANY_DETAILS_REQUEST = 'COMPANY_DETAILS_REQUEST';
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS';
export const COMPANY_DETAILS_FAIL = 'COMPANY_DETAILS_FAIL';
export const COMPANY_DETAILS_RESET = 'COMPANY_DETAILS_RESET';
